In [ ]:
import pandas as pd
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
df = pd.read_csv(
    "reddit_clean.csv"
)

df.head()

,Unnamed: 0,clean_comment,category,word_count
0,0,family mormon have never tried explain them t...,1,39
1,1,buddhism has very much lot compatible with chr...,1,196
2,2,seriously don say thing first all they won get...,-1,86
3,3,what you have learned yours and only yours wha...,0,29
4,4,for your own benefit you may want read living ...,1,112

In [ ]:
stop_words = set(
    stopwords.words('english')
)

stop_words = stop_words - {
    "not",
    "no",
    "but",
    "however",
    "yet"
}

In [ ]:
lemmatizer=WordNetLemmatizer()
def preprocess_text(text):

    # convert to string
    text = str(text)

    # lowercase
    text = text.lower()

    # remove leading/trailing spaces
    text = text.strip()

    # remove newlines
    text = re.sub(r'\n', ' ', text)

    # remove urls
    text = re.sub(r'http\S+', '', text)

    # keep only english chars and digits
    text = re.sub(
        r'[^A-Za-z0-9\s]',
        '',
        text
    )


    words = []

    for word in text.split():

        if word not in stop_words:
            words.append(
                lemmatizer.lemmatize(word)
            )

    return " ".join(words)

In [ ]:
df["clean_comment"] = df["clean_comment"].apply(preprocess_text)

In [ ]:
print(df.shape)

(37149, 4)

In [ ]:
df.head()

,Unnamed: 0,clean_comment,category,word_count
0,0,family mormon never tried explain still stare ...,1,39
1,1,buddhism much lot compatible christianity espe...,1,196
2,2,seriously say thing first get complex explain ...,-1,86
3,3,learned want teach different focus goal not wr...,0,29
4,4,benefit may want read living buddha living chr...,1,112

In [ ]:
df[df["clean_comment"].str.strip() == ""]

       Unnamed: 0 clean_comment  category  word_count
181           181                       0           0
288           288                       0           1
375           375                       0           0
392           392                       0           0
649           651                       0           0
...           ...           ...       ...         ...
36915       37012                       0           6
36946       37044                       0           0
36952       37050                       0          16
37086       37185                       0           1
37136       37235                       0           1

[271 rows x 4 columns]

In [ ]:
df = df[
    df["clean_comment"].str.strip() != ""
].copy()

In [ ]:
df[
    df["clean_comment"].str.strip() == ""
]

Empty DataFrame
Columns: [Unnamed: 0, clean_comment, category, word_count]
Index: []

In [ ]:
df.shape

(36878, 4)

In [ ]:
df["word_count"] = df["clean_comment"].apply(
    lambda x: len(x.split())
)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36878 entries, 0 to 37148
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     36878 non-null  int64
 1   clean_comment  36878 non-null  object
 2   category       36878 non-null  int64
 3   word_count     36878 non-null  int64
dtypes: int64(3), object(1)
memory usage: 1.4+ MB

In [ ]:
print(df.shape)

(36878, 4)

In [ ]:
df.to_csv(
    "reddit_preprocessed.csv",
    index=False
)